#!/bin/bash  

## Fill in config of program here.  
LOCAL=$(dirname `readlink -f $0`)
source $LOCAL/packingService.conf

USER=tao
CMDP_HOME=/opt/fbc/packingService
CMDP_PACKING="$CMDP_HOME/bin/packingService"
PROG_NAME=packingService

export TZ=UTC

get_Packing_PID() {
    echo "`ps aux|grep $PROG_NAME| grep -v grep|awk '{print $2}'`"
}

start() {
    # packingService
    if [[ $(get_Packing_PID) ]]; then
        echo "packingService already started"
    else
        ## Running the service
        su $USER -s /bin/bash -c "python $CMDP_PACKING -l $packing_loglevel -p $packing_http_retrycnt -k $packing_check_retrycnt -t $packing_threadnum -f $packing_logfile -c $center_dns -i $packing_time_diff > /dev/null &"
        echo "packingService program started"  
    fi  
}  

stop() { 
    # packingService
    if [[ $(get_Packing_PID) ]]; then
        ## Program is running, so stop it  
        pid="`get_Packing_PID`"
        kill $pid
        echo "packingService stopped"  
    else  
        ## Program is not running, exit with error.  
        echo "Error! packingService program not started!" 1>&2  
    fi  
}

status() {
    # packingService
    if [[ $(get_Packing_PID) ]]; then
        echo "packingService program is processing..."  
    else
        echo "packingService program stopped"
    fi
}

if [ "$(id -u)" != "0" ]; then  
    echo "This script must be run as root" 1>&2  
    exit 1  
fi  

case "$1" in  
    start)  
        start  
        exit 0  
    ;;  
    stop)  
        stop  
        exit 0  
    ;;  
    status)  
        status  
        exit 0  
    ;; 
    reload|restart|force-reload)  
        stop  
        start  
        exit 0  
    ;;  
    **)  
        echo "Usage: $0 {start|stop|status|reload}" 1>&2  
        exit 1  
    ;;  
esac
