#!/bin/bash

set -e

remove_bytecode()
{
    pkg=$1

    for file in `dpkg -L $pkg`;
    do
        if [ ! -d $file ]; then rm -rf $file; fi
    done
}

case "$1" in
        remove|remove-in-favour|deconfigure|deconfigure-in-favour|upgrade)
        /opt/fbc/packingService/init.d/packingService stop || true
        remove_bytecode fbc-packingService
        ;;
    deconfigure)
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac